export const recommendations = [
  // Outdoor activities
  {
    id: 1,
    category: "outdoor",
    name: "Beach Day",
    price: "low",
    image: new URL("../assets/images/beach-day.jpg", import.meta.url).href,
    info: "Enjoy the sun, sand, and sea.",
    credit: `Photo by <a href="https://unsplash.com/@andreahuls?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Andrea Huls Pareja</a> on <a href="https://unsplash.com/photos/a-group-of-people-sitting-on-top-of-a-sandy-beach-JuviRssBa6o?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 2,
    category: "outdoor",
    name: "Water Park",
    price: "mid",
    image: new URL("../assets/images/waterpark.jpg", import.meta.url).href,
    info: "Slides, pools, and fun!",
    credit: `Photo by <a href="https://unsplash.com/@yogasukma?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Yoga Sukma 🇮🇩</a> on <a href="https://unsplash.com/photos/a-group-of-people-riding-on-top-of-an-inflatable-raft-arG60-ye-V8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 3,
    category: "outdoor",
    name: "Swimming Pool",
    price: "low",
    image: new URL("../assets/images/swimming.jpg", import.meta.url).href,
    info: "Cool off with a swim.",
    credit: `Photo by <a href="https://unsplash.com/@davidoclubb?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Dave Clubb</a> on <a href="https://unsplash.com/photos/unicorn-floater-in-water-pool-x0BBA96B2x4?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 4,
    category: "outdoor",
    name: "Kayaking",
    price: "mid",
    image: new URL("../assets/images/kayaking.jpg", import.meta.url).href,
    info: "Paddle through water.",
    credit:
      'Photo by <a href="https://unsplash.com/@canismajoris?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Hatem Ramadan</a> on <a href="https://unsplash.com/photos/a-couple-of-people-on-a-kayak-in-the-water-bmt4RHJsB88?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 5,
    category: "outdoor",
    name: "Boating",
    price: "high",
    image: new URL("../assets/images/boating.jpg", import.meta.url).href,
    info: "Ride a boat on a lake or river.",
    credit: `Photo by <a href="https://unsplash.com/@owenroth_v1?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Owen Roth</a> on <a href="https://unsplash.com/photos/a-boat-in-the-water-with-a-mountain-in-the-background-xgXpQCmbqA0?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 6,
    category: "outdoor",
    name: "Sprinkler Fun",
    price: "low",
    image: new URL("../assets/images/sprinklers.jpg", import.meta.url).href,
    info: "Run through sprinklers in your yard.",
    credit: `Photo by <a href="https://unsplash.com/@rocinante_11?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Mick Haupt</a> on <a href="https://unsplash.com/photos/two-young-boys-playing-a-game-of-croquet-in-a-yard-YeplWEwVjbw?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 7,
    category: "outdoor",
    name: "Open Fire Hydrant",
    price: "low",
    image: new URL("../assets/images/hydrant.jpg", import.meta.url).href,
    info: "Cool off in the street water (if allowed).",
    credit: `Photo by <a href="https://unsplash.com/@kcky22?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Kristian</a> on <a href="https://unsplash.com/photos/a-fire-hydrant-spewing-water-on-a-city-street-jTIKikD6rT8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 8,
    category: "outdoor",
    name: "Camping by a Lake",
    price: "mid",
    image: new URL("../assets/images/lake.jpg", import.meta.url).href,
    info: "Enjoy nature and swim in the lake.",
    credit: `Photo by <a href="https://unsplash.com/@joeavocado?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Sean Martin</a> on <a href="https://unsplash.com/photos/green-trees-near-lake-under-blue-sky-during-daytime-8WOXpBfbT70?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 9,
    category: "outdoor",
    name: "Paddleboarding",
    price: "mid",
    image: new URL("../assets/images/paddleboarding.jpg", import.meta.url).href,
    info: "Paddle on calm waters.",
    client: `Photo by <a href="https://unsplash.com/@mattcoin?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Matt Zhou</a> on <a href="https://unsplash.com/photos/two-person-riding-on-paddle-boards-during-daytime-22qZVcUgD_U?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 10,
    category: "outdoor",
    name: "Boat Tubing",
    price: "high",
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Float down a river.",
    credit: `Photo by <a href="https://unsplash.com/@jessedo81?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">jesse orrico</a> on <a href="https://unsplash.com/photos/four-children-riding-inflatable-rafts-pulled-by-motorized-boat-jPRgMyLmxj0?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 11,
    category: "outdoor",
    name: "Outdoor Picnic",
    price: "low",
    image: new URL("../assets/images/picnic.jpg", import.meta.url).href,
    info: "Find a shaded spot and enjoy a meal.",
    credit: `Photo by <a href="https://unsplash.com/@number313?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Vianney CAHEN</a> on <a href="https://unsplash.com/photos/woman-in-white-shirt-sitting-beside-woman-in-white-shirt-gZJvqql3WdY?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 12,
    category: "outdoor",
    name: "Water Balloon Fight",
    price: "low",
    image: new URL("../assets/images/waterbaloon.jpg", import.meta.url).href,
    info: "Cool off with some fun water balloons.",
    credit: `Photo by <a href="https://unsplash.com/@aaronburden?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Aaron Burden</a> on <a href="https://unsplash.com/photos/macro-shot-of-toy-balloons-EwQvHL2ETx8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 13,
    category: "outdoor",
    name: "Slip 'n Slide",
    price: "low",
    image: new URL("../assets/images/slipandslide.jpg", import.meta.url).href,
    info: "Slide on a water-soaked plastic sheet.",
    credit: `Photo by <a href="https://unsplash.com/@lukeporter?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Luke Porter</a> on <a href="https://unsplash.com/photos/group-of-men-sliding-on-blue-canopy-mGFJIUD9yiM?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 14,
    category: "outdoor",
    name: "Visit a Botanical Garden",
    price: "mid",
    image: new URL("../assets/images/garden.jpg", import.meta.url).href,
    info: "Enjoy the beauty of plants in shaded areas.",
    credit: `Photo by <a href="https://unsplash.com/@bryandijkh?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Bryan Dijkhuizen</a> on <a href="https://unsplash.com/photos/a-walkway-through-a-lush-green-forest-filled-with-lots-of-trees-afCYU_ti5QU?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },

  // Indoor activities
  {
    id: 15,
    category: "indoor",
    name: "Movie Marathon",
    price: "low",
    image: new URL("../assets/images/movie.jpg", import.meta.url).href,
    info: "Watch movies in a cool room.",
    credit: `Photo by <a href="https://unsplash.com/@jenskreuter?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Jens Kreuter</a> on <a href="https://unsplash.com/photos/flat-screen-tv-ngMtsE5r9eI?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 16,
    category: "indoor",
    name: "Visit a Museum",
    price: "mid",
    image: new URL("../assets/images/musuem.jpg", import.meta.url).href,
    info: "Explore exhibits in air-conditioned comfort.",
    credit: `Photo by <a href="https://unsplash.com/@stoke1863?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Stephen Kidd</a> on <a href="https://unsplash.com/photos/a-large-room-with-people-and-stairs-8cF7iJ5iFh8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 17,
    category: "indoor",
    name: "Bowling",
    price: "mid",
    image: new URL("../assets/images/bowling.jpg", import.meta.url).href,
    info: "Enjoy a fun game indoors.",
    credit: `Photo by <a href="https://unsplash.com/@marcmll?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Marc Mueller</a> on <a href="https://unsplash.com/photos/macro-shot-of-assorted-bowling-balls-lwTSdfXfskE?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 18,
    category: "indoor",
    name: "Ice Skating",
    price: "mid",
    image: new URL("../assets/images/iceskating.jpg", import.meta.url).href,
    info: "Cool off on the ice.",
    credit: `Photo by <a href="https://unsplash.com/@getslower?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Andrew Solok</a> on <a href="https://unsplash.com/photos/a-group-of-people-skating-on-an-indoor-ice-rink-aLcKmRRgvYs?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },

  {
    id: 19,
    category: "indoor",
    name: "Billiards",
    price: "mid",
    image: new URL("../assets/images/billiards.jpg", import.meta.url).href,
    info: "Swim in a temperature-controlled environment.",
    credit: `Photo by <a href="https://unsplash.com/@andreevaleksandar?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Aleksandar Andreev</a> on <a href="https://unsplash.com/photos/a-pool-table-with-several-pool-balls-on-it-mjieNwWeY0Q?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 20,
    category: "indoor",
    name: "Arcade",
    price: "mid",
    image: new URL("../assets/images/arcade.jpg", import.meta.url).href,
    info: "Play games indoors.",
    credit: `Photo by <a href="https://unsplash.com/@mitchorr?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Mitchell Orr</a> on <a href="https://unsplash.com/photos/a-row-of-pinball-machines-sitting-next-to-each-other-bYYtehpPaeE?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 21,
    category: "indoor",
    name: "Visit an Aquarium",
    price: "mid",
    image: new URL("../assets/images/aquarium.jpg", import.meta.url).href,
    info: "Enjoy cool underwater exhibits.",
    credit: `Photo by <a href="https://unsplash.com/@goian?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Ian Schneider</a> on <a href="https://unsplash.com/photos/woman-standing-infront-of-aquarium-with-shoal-of-fish-0qpPV5nrhwo?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 22,
    category: "indoor",
    name: "Library",
    price: "low",
    image: new URL("../assets/images/library.jpg", import.meta.url).href,
    info: "Read books in a cool, quiet space.",
    credit: `Photo by <a href="https://unsplash.com/@itfeelslikefilm?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">🇸🇮 Janko Ferlič</a> on <a href="https://unsplash.com/photos/photo-of-library-with-turned-on-lights-sfL_QOnmy00?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 23,
    category: "indoor",
    name: "Trampoline Park",
    price: "mid",
    image: new URL("../assets/images/trampoline.jpg", import.meta.url).href,
    info: "Bounce around indoors.",
    credit: `Photo by Trista Peterson <a href="https://happilytrista.com/indoor-fun-at-altitude-trampoline-park/"></a>`,
  },
  {
    id: 24,
    category: "indoor",
    name: "Art Gallery",
    price: "mid",
    image: new URL("../assets/images/artgallery.jpg", import.meta.url).href,
    info: "Enjoy art in a cool environment.",
    credit: `Photo by <a href="https://unsplash.com/@zalfaimani?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Zalfa Imani</a> on <a href="https://unsplash.com/photos/woman-standing-in-front-of-paintings-DeTWuVp6prg?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 25,
    category: "indoor",
    name: "Escape Room",
    price: "mid",
    image: new URL("../assets/images/escape-room.jpg", import.meta.url).href,
    info: "Solve puzzles in an air-conditioned room.",
    credit: `Photo by <a href="https://unsplash.com/@kdwk?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Kdwk Leung</a> on <a href="https://unsplash.com/photos/brown-brick-wall-with-light-bulb-3oqHaTT_j8o?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 26,
    category: "indoor",
    name: "Indoor Mini Golf",
    price: "mid",
    image: new URL("../assets/images/minigolf.jpg", import.meta.url).href,
    info: "Play mini golf inside.",
    credit: `Photo by <a href="https://unsplash.com/@aaronburden?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Aaron Burden</a> on <a href="https://unsplash.com/photos/blue-golf-ball-8AplL8doB3A?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 27,
    category: "indoor",
    name: "Attend a Theater Show",
    price: "high",
    image: new URL("../assets/images/theater.jpg", import.meta.url).href,
    info: "Enjoy a performance in air conditioning.",
    credit: `Photo by <a href="https://unsplash.com/@dgmke_06?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Barry Weatherall</a> on <a href="https://unsplash.com/photos/red-and-yellow-stage-Hm_iFim94bw?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 28,
    category: "indoor",
    name: "Visit a Planetarium",
    price: "mid",
    image: new URL("../assets/images/planetarium.jpg", import.meta.url).href,
    info: "Learn about the stars in a cool, dark space.",
    credit: `Photo by <a href="https://unsplash.com/@30saul?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Saul Macias</a> on <a href="https://unsplash.com/photos/a-crowd-of-people-sitting-in-front-of-a-projector-screen-xA7_ZPTQXGM?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 29,
    category: "indoor",
    name: "Board Game Cafe",
    price: "low",
    image: new URL("../assets/images/cafe.jpg", import.meta.url).href,
    info: "Play board games in a cozy indoor setting.",
    credit: `Photo by <a href="https://unsplash.com/@antho_le?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Anthony LE</a> on <a href="https://unsplash.com/photos/a-couple-of-chairs-that-are-sitting-in-front-of-a-table-gdtu3zwVCb4?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 30,
    category: "indoor",
    name: "VR Gaming",
    price: "mid",
    image: new URL("../assets/images/vr-gaming.jpg", import.meta.url).href,
    info: "Play virtual reality games indoors.",
    credit: `Photo by <a href="https://unsplash.com/@viniciusamano?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Vinicius "amnx" Amano</a> on <a href="https://unsplash.com/photos/silhouette-of-man-standing-near-window-XOnbUXqILzA?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },

  // Drinks
  {
    id: 31,
    category: "drinks",
    name: "Iced Tea",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Refreshing and cool.",
    credit: ``,
  },
  {
    id: 32,
    category: "drinks",
    name: "Smoothie",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Healthy and delicious.",
    credit: ``,
  },
  {
    id: 33,
    category: "drinks",
    name: "Coconut Water",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Hydrating and refreshing.",
    credit: ``,
  },
  {
    id: 34,
    category: "drinks",
    name: "Cold Brew Coffee",
    price: "low",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Chilled and caffeinated.",
    credit: ``,
  },
  {
    id: 35,
    category: "drinks",
    name: "Herbal Iced Tea",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Cooling and caffeine-free.",
    credit: ``,
  },
  {
    id: 36,
    category: "drinks",
    name: "Infused Water",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Water with fruit or herbs.",
    credit: ``,
  },
  {
    id: 37,
    category: "drinks",
    name: "Iced Lemonade",
    price: "low",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Tart and refreshing.",
    credit: ``,
  },
  {
    id: 38,
    category: "drinks",
    name: "Iced Latte",
    price: "low",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Chilled and creamy.",
    credit: ``,
  },
  {
    id: 39,
    category: "drinks",
    name: "Watermelon Juice",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Hydrating and sweet.",
    credit: ``,
  },
  {
    id: 40,
    category: "drinks",
    name: "Mint Julep",
    price: "mid",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Cool and minty.",
    credit: ``,
  },
  {
    id: 41,
    category: "drinks",
    name: "Iced Matcha",
    price: "mid",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Chilled and healthy.",
    credit: ``,
  },
  {
    id: 42,
    category: "drinks",
    name: "Iced Herbal Tea",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Cooling and caffeine-free.",
    credit: ``,
  },
  {
    id: 43,
    category: "drinks",
    name: "Iced Mocha",
    price: "mid",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Chilled and chocolaty.",
    credit: ``,
  },
  {
    id: 44,
    category: "drinks",
    name: "Iced Green Tea",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Refreshing and healthy.",
    credit: ``,
  },
  {
    id: 45,
    category: "drinks",
    name: "Frozen Margaritas",
    price: "mid",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Chilled and alcoholic.",
    credit: ``,
  },
  {
    id: 46,
    category: "drinks",
    name: "Iced Chai Latte",
    price: "mid",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Spiced and chilled.",
    credit: ``,
  },
  {
    id: 47,
    category: "drinks",
    name: "Iced Apple Cider",
    price: "low",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Refreshing and sweet.",
    credit: ``,
  },
  {
    id: 48,
    category: "drinks",
    name: "Frozen Lemonade",
    price: "low",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Tart and frozen.",
    credit: ``,
  },
  {
    id: 49,
    category: "drinks",
    name: "Iced Almond Milk",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Refreshing and dairy-free.",
    credit: ``,
  },
  {
    id: 50,
    category: "drinks",
    name: "Iced Herbal Infusions",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Cooling and caffeine-free.",
    credit: ``,
  },

  // Food
  {
    id: 51,
    category: "food",
    name: "Frozen Yogurt",
    price: "low",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Cool and creamy treat.",
    credit: ``,
  },
  {
    id: 52,
    category: "food",
    name: "Popsicles",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Icy and refreshing.",
    credit: ``,
  },
  {
    id: 53,
    category: "food",
    name: "Gazpacho",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Cold soup to cool off.",
    credit: ``,
  },
  {
    id: 54,
    category: "food",
    name: "Fruit Salad",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Sweet and hydrating.",
    credit: ``,
  },
  {
    id: 55,
    category: "food",
    name: "Sorbet",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Light and icy.",
    credit: ``,
  },
  {
    id: 56,
    category: "food",
    name: "Ice Cream",
    price: "low",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Cool and creamy treat.",
    credit: ``,
  },
  {
    id: 57,
    category: "food",
    name: "Watermelon",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Hydrating and sweet.",
    credit: ``,
  },
  {
    id: 58,
    category: "food",
    name: "Ice Pops",
    price: "low",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Icy and sweet.",
    credit: ``,
  },
  {
    id: 59,
    category: "food",
    name: "Smoothie Bowls",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Healthy and refreshing.",
    credit: ``,
  },
  {
    id: 60,
    category: "food",
    name: "Frozen Berries",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Icy and sweet snack.",
    credit: ``,
  },
  {
    id: 61,
    category: "food",
    name: "Frozen Grapes",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Icy and sweet snack.",
    credit: ``,
  },
  {
    id: 62,
    category: "food",
    name: "Cold Quinoa Salad",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Refreshing and nutritious.",
    credit: ``,
  },
  {
    id: 63,
    category: "food",
    name: "Frozen Banana Bites",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Icy and sweet snack.",
    credit: ``,
  },
  {
    id: 64,
    category: "food",
    name: "Chilled Gazpacho",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Cool and refreshing soup.",
    credit: ``,
  },
  {
    id: 65,
    category: "food",
    name: "Frozen Mochi",
    price: "low",
    healthy: false,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Icy and chewy treat.",
    credit: ``,
  },
  {
    id: 66,
    category: "food",
    name: "Chilled Cucumber Soup",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Cool and refreshing.",
    credit: ``,
  },
  {
    id: 67,
    category: "food",
    name: "Frozen Smoothie Packs",
    price: "low",
    healthy: true,
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Pre-made and icy.",
    credit: ``,
  },
];
