export const recommendations = [
  // Outdoor activities
  {
    id: 1,
    category: "outdoor",
    name: "Beach Day",
    price: "low",
    image: new URL("../assets/images/beach-day.jpg", import.meta.url).href,
    info: "Enjoy the sun, sand, and sea.",
    credit: `Photo by <a href="https://unsplash.com/@andreahuls?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Andrea Huls Pareja</a> on <a href="https://unsplash.com/photos/a-group-of-people-sitting-on-top-of-a-sandy-beach-JuviRssBa6o?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 2,
    category: "outdoor",
    name: "Water Park",
    price: "mid",
    image: new URL("../assets/images/waterpark.jpg", import.meta.url).href,
    info: "Slides, pools, and fun!",
    credit: `Photo by <a href="https://unsplash.com/@yogasukma?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Yoga Sukma 🇮🇩</a> on <a href="https://unsplash.com/photos/a-group-of-people-riding-on-top-of-an-inflatable-raft-arG60-ye-V8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 3,
    category: "outdoor",
    name: "Swimming Pool",
    price: "low",
    image: new URL("../assets/images/swimming.jpg", import.meta.url).href,
    info: "Cool off with a swim.",
    credit: `Photo by <a href="https://unsplash.com/@davidoclubb?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Dave Clubb</a> on <a href="https://unsplash.com/photos/unicorn-floater-in-water-pool-x0BBA96B2x4?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 4,
    category: "outdoor",
    name: "Kayaking",
    price: "mid",
    image: new URL("../assets/images/kayaking.jpg", import.meta.url).href,
    info: "Paddle through water.",
    credit:
      'Photo by <a href="https://unsplash.com/@canismajoris?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Hatem Ramadan</a> on <a href="https://unsplash.com/photos/a-couple-of-people-on-a-kayak-in-the-water-bmt4RHJsB88?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>',
  },
  {
    id: 5,
    category: "outdoor",
    name: "Boating",
    price: "high",
    image: new URL("../assets/images/boating.jpg", import.meta.url).href,
    info: "Ride a boat on a lake or river.",
    credit: `Photo by <a href="https://unsplash.com/@owenroth_v1?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Owen Roth</a> on <a href="https://unsplash.com/photos/a-boat-in-the-water-with-a-mountain-in-the-background-xgXpQCmbqA0?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 6,
    category: "outdoor",
    name: "Sprinkler Fun",
    price: "low",
    image: new URL("../assets/images/sprinklers.jpg", import.meta.url).href,
    info: "Run through sprinklers in your yard.",
    credit: `Photo by <a href="https://unsplash.com/@rocinante_11?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Mick Haupt</a> on <a href="https://unsplash.com/photos/two-young-boys-playing-a-game-of-croquet-in-a-yard-YeplWEwVjbw?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 7,
    category: "outdoor",
    name: "Open Fire Hydrant",
    price: "low",
    image: new URL("../assets/images/hydrant.jpg", import.meta.url).href,
    info: "Cool off in the street water (if allowed).",
    credit: `Photo by <a href="https://unsplash.com/@kcky22?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Kristian</a> on <a href="https://unsplash.com/photos/a-fire-hydrant-spewing-water-on-a-city-street-jTIKikD6rT8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 8,
    category: "outdoor",
    name: "Camping by a Lake",
    price: "mid",
    image: new URL("../assets/images/lake.jpg", import.meta.url).href,
    info: "Enjoy nature and swim in the lake.",
    credit: `Photo by <a href="https://unsplash.com/@joeavocado?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Sean Martin</a> on <a href="https://unsplash.com/photos/green-trees-near-lake-under-blue-sky-during-daytime-8WOXpBfbT70?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 9,
    category: "outdoor",
    name: "Paddleboarding",
    price: "mid",
    image: new URL("../assets/images/paddleboarding.jpg", import.meta.url).href,
    info: "Paddle on calm waters.",
    client: `Photo by <a href="https://unsplash.com/@mattcoin?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Matt Zhou</a> on <a href="https://unsplash.com/photos/two-person-riding-on-paddle-boards-during-daytime-22qZVcUgD_U?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 10,
    category: "outdoor",
    name: "Boat Tubing",
    price: "high",
    image: new URL("../assets/images/tubing.jpg", import.meta.url).href,
    info: "Float down a river.",
    credit: `Photo by <a href="https://unsplash.com/@jessedo81?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">jesse orrico</a> on <a href="https://unsplash.com/photos/four-children-riding-inflatable-rafts-pulled-by-motorized-boat-jPRgMyLmxj0?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
    `,
  },
  {
    id: 11,
    category: "outdoor",
    name: "Outdoor Picnic",
    price: "low",
    image: "insert image here",
    info: "Find a shaded spot and enjoy a meal.",
  },
  {
    id: 12,
    category: "outdoor",
    name: "Water Balloon Fight",
    price: "low",
    image: "insert image here",
    info: "Cool off with some fun water balloons.",
  },
  {
    id: 13,
    category: "outdoor",
    name: "Slip 'n Slide",
    price: "low",
    image: "insert image here",
    info: "Slide on a water-soaked plastic sheet.",
  },
  {
    id: 14,
    category: "outdoor",
    name: "Visit a Botanical Garden",
    price: "mid",
    image: "insert image here",
    info: "Enjoy the beauty of plants in shaded areas.",
  },

  // Indoor activities
  {
    id: 15,
    category: "indoor",
    name: "Movie Marathon",
    price: "low",
    image: "insert image here",
    info: "Watch movies in a cool room.",
  },
  {
    id: 16,
    category: "indoor",
    name: "Visit a Museum",
    price: "mid",
    image: "insert image here",
    info: "Explore exhibits in air-conditioned comfort.",
  },
  {
    id: 17,
    category: "indoor",
    name: "Bowling",
    price: "mid",
    image: "insert image here",
    info: "Enjoy a fun game indoors.",
  },
  {
    id: 18,
    category: "indoor",
    name: "Ice Skating",
    price: "mid",
    image: "insert image here",
    info: "Cool off on the ice.",
  },

  {
    id: 19,
    category: "indoor",
    name: "Indoor Pool",
    price: "mid",
    image: "insert image here",
    info: "Swim in a temperature-controlled environment.",
  },
  {
    id: 20,
    category: "indoor",
    name: "Arcade",
    price: "mid",
    image: "insert image here",
    info: "Play games indoors.",
  },
  {
    id: 21,
    category: "indoor",
    name: "Visit an Aquarium",
    price: "mid",
    image: "insert image here",
    info: "Enjoy cool underwater exhibits.",
  },
  {
    id: 22,
    category: "indoor",
    name: "Library",
    price: "low",
    image: "insert image here",
    info: "Read books in a cool, quiet space.",
  },
  {
    id: 23,
    category: "indoor",
    name: "Trampoline Park",
    price: "mid",
    image: "insert image here",
    info: "Bounce around indoors.",
  },
  {
    id: 24,
    category: "indoor",
    name: "Art Gallery",
    price: "mid",
    image: "insert image here",
    info: "Enjoy art in a cool environment.",
  },
  {
    id: 25,
    category: "indoor",
    name: "Escape Room",
    price: "mid",
    image: "insert image here",
    info: "Solve puzzles in an air-conditioned room.",
  },
  {
    id: 26,
    category: "indoor",
    name: "Indoor Mini Golf",
    price: "mid",
    image: "insert image here",
    info: "Play mini golf inside.",
  },
  {
    id: 27,
    category: "indoor",
    name: "Cooking Class",
    price: "mid",
    image: "insert image here",
    info: "Learn to cook in a cool kitchen.",
  },
  {
    id: 28,
    category: "indoor",
    name: "Attend a Theater Show",
    price: "high",
    image: "insert image here",
    info: "Enjoy a performance in air conditioning.",
  },
  {
    id: 29,
    category: "indoor",
    name: "Gym",
    price: "low",
    image: "insert image here",
    info: "Work out in a climate-controlled environment.",
  },
  {
    id: 30,
    category: "indoor",
    name: "Indoor Rock Climbing",
    price: "mid",
    image: "insert image here",
    info: "Climb walls in a cool indoor facility.",
  },
  {
    id: 31,
    category: "indoor",
    name: "Dance Class",
    price: "mid",
    image: "insert image here",
    info: "Learn to dance in air conditioning.",
  },
  {
    id: 32,
    category: "indoor",
    name: "Visit a Science Center",
    price: "mid",
    image: "insert image here",
    info: "Explore science exhibits indoors.",
  },
  {
    id: 33,
    category: "indoor",
    name: "Visit a Planetarium",
    price: "mid",
    image: "insert image here",
    info: "Learn about the stars in a cool, dark space.",
  },
  {
    id: 34,
    category: "indoor",
    name: "Board Game Cafe",
    price: "low",
    image: "insert image here",
    info: "Play board games in a cozy indoor setting.",
  },
  {
    id: 35,
    category: "indoor",
    name: "Pottery Class",
    price: "mid",
    image: "insert image here",
    info: "Create pottery in a cool studio.",
  },
  {
    id: 36,
    category: "indoor",
    name: "Indoor Kart Racing",
    price: "mid",
    image: "insert image here",
    info: "Race go-karts in an air-conditioned track.",
  },
  {
    id: 37,
    category: "indoor",
    name: "VR Gaming",
    price: "mid",
    image: "insert image here",
    info: "Play virtual reality games indoors.",
  },
  {
    id: 38,
    category: "indoor",
    name: "Visit a Historical Site",
    price: "mid",
    image: "insert image here",
    info: "Learn history in air-conditioned comfort.",
  },

  // Drinks
  {
    id: 39,
    category: "drinks",
    name: "Iced Tea",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Refreshing and cool.",
  },
  {
    id: 40,
    category: "drinks",
    name: "Smoothie",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Healthy and delicious.",
  },
  {
    id: 41,
    category: "drinks",
    name: "Coconut Water",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Hydrating and refreshing.",
  },
  {
    id: 42,
    category: "drinks",
    name: "Cold Brew Coffee",
    price: "low",
    healthy: false,
    image: "insert image here",
    info: "Chilled and caffeinated.",
  },
  {
    id: 43,
    category: "drinks",
    name: "Herbal Iced Tea",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Cooling and caffeine-free.",
  },
  {
    id: 44,
    category: "drinks",
    name: "Infused Water",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Water with fruit or herbs.",
  },
  {
    id: 45,
    category: "drinks",
    name: "Iced Lemonade",
    price: "low",
    healthy: false,
    image: "insert image here",
    info: "Tart and refreshing.",
  },
  {
    id: 46,
    category: "drinks",
    name: "Iced Latte",
    price: "low",
    healthy: false,
    image: "insert image here",
    info: "Chilled and creamy.",
  },
  {
    id: 47,
    category: "drinks",
    name: "Watermelon Juice",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Hydrating and sweet.",
  },
  {
    id: 48,
    category: "drinks",
    name: "Mint Julep",
    price: "mid",
    healthy: false,
    image: "insert image here",
    info: "Cool and minty.",
  },
  {
    id: 49,
    category: "drinks",
    name: "Iced Matcha",
    price: "mid",
    healthy: true,
    image: "insert image here",
    info: "Chilled and healthy.",
  },
  {
    id: 50,
    category: "drinks",
    name: "Iced Herbal Tea",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Cooling and caffeine-free.",
  },
  {
    id: 51,
    category: "drinks",
    name: "Iced Mocha",
    price: "mid",
    healthy: false,
    image: "insert image here",
    info: "Chilled and chocolaty.",
  },
  {
    id: 52,
    category: "drinks",
    name: "Iced Green Tea",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Refreshing and healthy.",
  },
  {
    id: 53,
    category: "drinks",
    name: "Frozen Margaritas",
    price: "mid",
    healthy: false,
    image: "insert image here",
    info: "Chilled and alcoholic.",
  },
  {
    id: 54,
    category: "drinks",
    name: "Iced Chai Latte",
    price: "mid",
    healthy: false,
    image: "insert image here",
    info: "Spiced and chilled.",
  },
  {
    id: 55,
    category: "drinks",
    name: "Iced Apple Cider",
    price: "low",
    healthy: false,
    image: "insert image here",
    info: "Refreshing and sweet.",
  },
  {
    id: 56,
    category: "drinks",
    name: "Frozen Lemonade",
    price: "low",
    healthy: false,
    image: "insert image here",
    info: "Tart and frozen.",
  },
  {
    id: 57,
    category: "drinks",
    name: "Iced Almond Milk",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Refreshing and dairy-free.",
  },
  {
    id: 58,
    category: "drinks",
    name: "Iced Herbal Infusions",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Cooling and caffeine-free.",
  },

  // Food
  {
    id: 59,
    category: "food",
    name: "Frozen Yogurt",
    price: "low",
    healthy: false,
    image: "insert image here",
    info: "Cool and creamy treat.",
  },
  {
    id: 60,
    category: "food",
    name: "Popsicles",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Icy and refreshing.",
  },
  {
    id: 61,
    category: "food",
    name: "Gazpacho",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Cold soup to cool off.",
  },
  {
    id: 62,
    category: "food",
    name: "Fruit Salad",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Sweet and hydrating.",
  },
  {
    id: 63,
    category: "food",
    name: "Sorbet",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Light and icy.",
  },
  {
    id: 64,
    category: "food",
    name: "Ice Cream",
    price: "low",
    healthy: false,
    image: "insert image here",
    info: "Cool and creamy treat.",
  },
  {
    id: 65,
    category: "food",
    name: "Watermelon",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Hydrating and sweet.",
  },
  {
    id: 66,
    category: "food",
    name: "Ice Pops",
    price: "low",
    healthy: false,
    image: "insert image here",
    info: "Icy and sweet.",
  },
  {
    id: 67,
    category: "food",
    name: "Smoothie Bowls",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Healthy and refreshing.",
  },
  {
    id: 68,
    category: "food",
    name: "Frozen Berries",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Icy and sweet snack.",
  },
  {
    id: 69,
    category: "food",
    name: "Frozen Grapes",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Icy and sweet snack.",
  },
  {
    id: 70,
    category: "food",
    name: "Cold Quinoa Salad",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Refreshing and nutritious.",
  },
  {
    id: 71,
    category: "food",
    name: "Frozen Banana Bites",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Icy and sweet snack.",
  },
  {
    id: 72,
    category: "food",
    name: "Chilled Gazpacho",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Cool and refreshing soup.",
  },
  {
    id: 73,
    category: "food",
    name: "Frozen Mochi",
    price: "low",
    healthy: false,
    image: "insert image here",
    info: "Icy and chewy treat.",
  },
  {
    id: 74,
    category: "food",
    name: "Chilled Cucumber Soup",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Cool and refreshing.",
  },
  {
    id: 75,
    category: "food",
    name: "Frozen Smoothie Packs",
    price: "low",
    healthy: true,
    image: "insert image here",
    info: "Pre-made and icy.",
  },
];
